apiVersion: v1
kind: Pod
metadata:
  name: httpd-init
  labels:
    app: httpd-init
spec:
  initContainers:
  - image: hectorvido/git
    name: cloner
    command:
    - git
    - clone
    - 'https://github.com/hector-vido/sti-lighttpd.git'
    - '/usr/local/apache2/htdocs'
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: html
  - image: busybox
    name: cleaner
    command: ["rm", "-rf", "/usr/local/apache2/htdocs/.git"]
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: html
  containers:
  - image: httpd:alpine
    name: httpd
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: html
  volumes:
  - name: html
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-init
spec:
  selector:
    app: httpd-init
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
