---
apiVersion: v1
kind: Pod
metadata:
  name: limited-pod6
  namespace: dexter-limits
spec:
  containers:
  - name: limited-pod6
    image: nginx
    resources:
      limits:
        memory: "2Gi"
        cpu: 1.2
      requests:
        memory: "1.3Gi"
        cpu: 0.8
  nodeSelector:
    cloud: AWS
