---
apiVersion: v1
kind: Pod
metadata:
  name: limited-pod4
  namespace: dexter-limits
spec:
  containers:
  - name: limited-pod4
    image: nginx
    resources:
      limits:
        memory: "900Mi"
        cpu: 0.7
      requests:
        memory: "600Mi"
        cpu: 0.4
  nodeSelector:
    cloud: AWS
