---
apiVersion: v1
kind: Pod
metadata:
  name: limited-pod2
  namespace: dexter-limits
spec:
  containers:
  - name: limited-pod2
    image: nginx
    resources:
      requests:
        memory: "512Mi"
        cpu: 0.6
  nodeSelector:
    cloud: AWS
