---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /backup
      name: backup-volume
  volumes:
  - name: backup-volume
    hostPath:
      path: /home/vagrant
      type: Directory
  nodeSelector:
    cloud: AZURE
