---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/vagrant/wordpress-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: monitoring
          operator: In
          values:
            - prometheus
